name: HAProxyDetector
main: io.wdsj.haproxydetector.bukkit.BukkitMain
version: ${project.version}
author: 0D00_0721
load: STARTUP
depend: [ProtocolLib]
# This plugin is universal and should support every Minecraft version.
# If you're getting errors regarding the API version, feel free to change it to whatever you want.
api-version: 1.13
awareness:
    - !@UTF8
